
export const baseUrl = "http://localhost:8080"

const SummaryApi = {
    register:{
        url:'/api/users/register',
        method:'post'
    },
    login:{
        url:'/api/users/login',
        method:'post'
    },
    ForgotPassword:{
        url:'/api/users/forgot-password',
        method:'put'
    },
    VerifyForgotPasswordOtp:{
        url:'/api/users/verify-forgot-password-otp',
        method:'put'
    },
    ResetPassword:{
        url:'/api/users/reset-password',
        method:'put'
    },
    refreshToken:{
        url:'/api/users/refresh-token',
        method:'post'
    },
    userDetails:{
        url:'/api/users/user-details',
        method:'get'
    },
    logout:{
        url:'/api/users/logout',
        method:'post'
    },
    uploadAvatar:{
        url:'/api/users/upload-avatar',
        method:'put'
    },
    updateUser:{
        url:'/api/users/update-user',
        method:'put'
    },
    deleteAvatar:{
        url:'/api/users/deleteAvatar',
        method:'delete'
    },
    addCategory:{
        url:'/api/category/add-category',
        method : 'post'
    },
    uploadImage:{
        url:'/api/file/upload',
        method : 'post'
    },
    getCategory:{
        url:'/api/category/get',
        method:'get'
    },
    updateCategory:{
        url:'/api/category/update',
        method:'put'
    },
    deleteCategory:{
        url:'/api/category/delete',
        method:'delete'
    },
    createSubCategory:{
        url:'/api/subCategory/create',
        method:'post'
    },
    getSubCategory:{
        url:'/api/subCategory/get',
        method:'post'
    },
    updateSubCategory:{
        url:'/api/subCategory/update',
        method:'put'
    },
    deleteSubCategory:{
        url:'/api/subCategory/delete',
        method:'delete'
    },
    createProduct:{
        url:'/api/product/create',
        method:'post'
    },
    getProduct:{
        url:'/api/product/get',
        method:'post'
    },
}
export default SummaryApi